version: "3"
services:
  my-own-mysql:
    image: mysql:8.0
    container_name: my-own-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysqlDBData:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  my-own-phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: my-own-phpmyadmin
    links:
      - 'my-own-mysql:db'
    ports:
      - '8081:80'
      
  projecte:
    image: springbootapp:0.0.1-SNAPSHOT
    container_name: itic-web-projecte
    ports:
      - "8080:8080"
    depends_on:
      - my-own-mysql

volumes:
  mysqlDBData:
