version: "3"
services:
  mariadb:
    container_name: my-own-mysql
    image: docker.io/bitnami/mariadb:11.1
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_DATABASE=biblioteca_online

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_projecte
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
      
  projecte:
    image: springbootapp:0.0.1-SNAPSHOT
    container_name: itic-web-projecte
    ports:
      - "8080:8080"
    depends_on:
      - mariadb